site_name: Layan's Digital Garden
site_description: A collection of notes and resources on various topics.
site_url: https://layanbindayel.github.io/digitalGarden/
copyright: ©️ 2026 Layan Bin Dayel · All rights reserved 

theme:
  name: material
  # favicon:

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

  palette:
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    logo: material/server

  font:
    text: Inter
    code: Fira Code
nav:
  - Home: index.md
  - Academics:
      - "AI & Data Science": Academics/ai-ds/Intro.md
      - "Open Academics": Academics/Intro.md
  - Career Development:
      - "Career Development": career-development/Intro.md
  - Academic Plan: academic-plan.md
  - Resources: links.md
  - About: 
      - "About Me": about.md
      - "Contact": contact.md
      - Copyright & License: copyright-license.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      # emoji_index: !!python/name:material.extensions.emoji.twemoji
      # emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search

extra_css:
  - styles/extra.css

extra_javascript:
  - javascript/cta-footer.js